<a href="https://colab.research.google.com/github/biplavdotcom/ML_from_Scratch/blob/main/01%20Introduction_to_ML/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introduction to numpy


## Single dimension array ✅

In [ ]:
import numpy as np

In [ ]:
var = np.zeros(5)
print(type(var))

<class 'numpy.ndarray'>


In [ ]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
np.full(10,3)

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

### np arrays

In [ ]:
nums = np.array([1, 2, 3, 4])

In [ ]:
nums[2] = 5
nums

array([1, 2, 5, 4])

In [ ]:
#

In [ ]:
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

### Create arrays with evenly spaced numbers within a specified range

In [ ]:
np.linspace(0, 100, 10)

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

## Multidimensional array ✅

In [ ]:
np.zeros((5, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:
np.ones((5, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

### Create an MD unit Array of size (5, 2), Generate a random array of size (3, 5) with elements of your choice, Update the element of an array with index

In [ ]:
np.ones((5,2))


array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [ ]:
md = np.array([
     [1, 2, 3, 4, 5],
     [3, 4, 5, 3, 6],
     [6, 3, 4, 8, 0]
     ])

In [ ]:
md

array([[1, 2, 3, 4, 5],
       [3, 4, 5, 3, 6],
       [6, 3, 4, 8, 0]])

In [ ]:
md[0,1] = 10
md[1,4] = 8
md

array([[ 1, 10,  3,  4,  5],
       [ 3,  4,  5,  3,  8],
       [ 6,  3,  4,  8,  0]])

In [ ]:
md[2] = np.ones(5)
md

array([[ 1, 10,  3,  4,  5],
       [ 3,  4,  5,  3,  8],
       [ 1,  1,  1,  1,  1]])

In [ ]:
md[:,4] = [2, 2, 2]         # : -> no row taken
md

array([[ 1, 10,  3,  4,  2],
       [ 3,  4,  5,  3,  2],
       [ 1,  1,  1,  1,  2]])

## Randomly generated arrays ✅

- Numpy can create arrays filled with random numbers
- To ensure the reproductibility, you can set a seed using np.random.seed()
- Everytime you run the code with np.random.seed(2), it will generate the exact same random numbers.
- If you remove or change the seed values, the sequence of random numbers will be changed

In [ ]:
np.random.rand(3)

array([0.06765181, 0.81614482, 0.92957488])

In [ ]:
np.random.seed(5)
np.random.rand(5)

array([0.22199317, 0.87073231, 0.20671916, 0.91861091, 0.48841119])

In [ ]:
np.random.seed(5)
np.random.rand(5,2)

array([[0.22199317, 0.87073231],
       [0.20671916, 0.91861091],
       [0.48841119, 0.61174386],
       [0.76590786, 0.51841799],
       [0.2968005 , 0.18772123]])

In [165]:
np.random.randn(5,2)

array([[-1.27962318,  0.03654264],
       [-0.64635659,  0.54856784],
       [ 0.21054246,  0.34650175],
       [-0.56705117,  0.41367881],
       [-0.51025606,  0.51725935]])

In [175]:
np.random.seed(42)
np.random.randint(low = 0, high = 100, size = (5,2))

array([[51, 92],
       [14, 71],
       [60, 20],
       [82, 86],
       [74, 74]])

## Element wise operation

In [176]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [177]:
b = (10 + (a*2))
b

array([10, 12, 14, 16, 18])

## Comparison operations
- You can perform element wise comparisons and create boolean arrays

In [179]:
a

array([0, 1, 2, 3, 4])

In [182]:
a >= 2

array([False, False,  True,  True,  True])

In [184]:
a > b

array([False, False, False, False, False])

## Summarizing
- Numpy provides functions for summarizing arrays of data

In [185]:
a

array([0, 1, 2, 3, 4])

In [187]:
# Standard deviavtion
a.std()

1.4142135623730951

In [189]:
# Minimum value of an array
a.min()

0

In [191]:
# Max value of an array
a.max()

4

In [192]:
# Sum of the elements of an array
a.sum()

10